
import Footer from '@/components/Footer/Footer'
import './globals.css'
import Header from '@/components/Header/Header'
import ContextProvider from '@/components/ContextProvider'
export const metadata = {
  title: 'Dealive',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <ContextProvider children={children} />

      </body>
    </html>
  )
}
