
import Footer from '@/components/Footer/Footer'
import './globals.css'
import Header from '@/components/Header/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='wrapper'>
          <Header />
          <div className='content'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
